[package]
name = "god"
version = "0.0.1"
edition = "2021"
license = "MPL-2.0"
description = "See it all."
repository = "https://github.com/npxTSC/god/"
keywords = ["osint", "dossier"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
